function getExibitions() {
  return [
    {
      title: "PIEDZIMIS PIEDERĪGS",
      description: "Mēs visi esam tik atšķirīgi un tomēr tik līdzīgi.",
      image: "/images/atklatiesNoJauna/16. Kristine123.jpg",
      longDescription:
        " Fotoizstādē “Piedzimis piederīgs?” 20 portretos attēloti cilvēki ar garīga rakstura traucējumiem un viņu atziņas. Ar izstādi aktualizējam mūsu pārliecību, ka visi esam tik atšķirīgi un tomēr tik līdzīgi. Fotomākslinieks Valters Poļakovs. Idejas autors Pēteris Martukāns. Ventspilī, Pārventas bibliotēkā no 16. septembra līdz 8. oktobrim. Līgatnē, Zeit mākslas telpā no 1. decembra līdz 31. decembrim. Rīgā, Latvijas Nacionālajā  bibliotēkā no 18. janvāra līdz. 18. februārim. Izstāde tapusi projekta “Bērni nepiedzimst ar aizspriedumiem” ietvaros,kurš Latvijā tiek īstenots sadarbībā ar Glada Hudik teātra apvienību, Zviedrijas vēstniecību un Zviedrijas institūta finansiālu atbalstu.",
      images: [
        "/images/atklatiesNoJauna/3. Helvis.jpg",
        "/images/atklatiesNoJauna/helvis.jpg",
        "/images/atklatiesNoJauna/3B4A9548.jpg",
        "/images/atklatiesNoJauna/alekss.jpg",
        "/images/atklatiesNoJauna/15. Aleks.jpg",
        "/images/atklatiesNoJauna/3B4A4637.jpg",
        "/images/atklatiesNoJauna/5. Vadims labots.jpg",
        "/images/atklatiesNoJauna/vadims.jpg",
        "/images/atklatiesNoJauna/3B4A0846.jpg",
        "/images/atklatiesNoJauna/Adrija.jpg",
        "/images/atklatiesNoJauna/7. Adrija.jpg",
        "/images/atklatiesNoJauna/3B4A4693.jpg",
        "/images/atklatiesNoJauna/6. Sandris.jpg",
        "/images/atklatiesNoJauna/Sandris.jpg",
        "/images/atklatiesNoJauna/3B4A4661.jpg",
        "/images/atklatiesNoJauna/Kristine.jpg",
        "/images/atklatiesNoJauna/16. Kristine123.jpg",
        "/images/atklatiesNoJauna/3B4A4673.jpg",
        "/images/atklatiesNoJauna/10. Agnis1.jpg",
        "/images/atklatiesNoJauna/Agnis.jpg",
        "/images/atklatiesNoJauna/3B4A4673.jpg",
        "/images/atklatiesNoJauna/deniss.jpg",
        "/images/atklatiesNoJauna/20. Deniss.jpg",
        "/images/atklatiesNoJauna/3B4A4673.jpg",
        "/images/atklatiesNoJauna/3B4A1852.jpg",
        "/images/atklatiesNoJauna/evija.jpg",
        "/images/atklatiesNoJauna/3B4A4673.jpg",
        "/images/atklatiesNoJauna/ivans.jpg",
        "/images/atklatiesNoJauna/8. Ivans.jpg",
        "/images/atklatiesNoJauna/3B4A4673.jpg",
        "/images/atklatiesNoJauna/19. Kaspars.jpg",
        "/images/atklatiesNoJauna/kaspars2.jpg",
        "/images/atklatiesNoJauna/3B4A4673.jpg",
        "/images/atklatiesNoJauna/Samanta.jpg",
        "/images/atklatiesNoJauna/18. Samanta.jpg",
        "/images/atklatiesNoJauna/3B4A4673.jpg",
        "/images/atklatiesNoJauna/9. Kaspars.jpg",
        "/images/atklatiesNoJauna/Kaspars.jpg",
        "/images/atklatiesNoJauna/3B4A4673.jpg",
        "/images/atklatiesNoJauna/Aldis.jpg",
        "/images/atklatiesNoJauna/2. Aldis.jpg",
        "/images/atklatiesNoJauna/3B4A4673.jpg",
        "/images/atklatiesNoJauna/3B4A9153.jpg",
        "/images/atklatiesNoJauna/marcis.jpg",
        "/images/atklatiesNoJauna/3B4A4673.jpg",
        "/images/atklatiesNoJauna/einars.jpg",
        "/images/atklatiesNoJauna/4. Einars1.jpg",
        "/images/atklatiesNoJauna/3B4A4673.jpg",
        "/images/atklatiesNoJauna/3B4A2328.jpg",
        "/images/atklatiesNoJauna/zenija.jpg",
        "/images/atklatiesNoJauna/3B4A4673.jpg",
        "/images/atklatiesNoJauna/aivars.jpg",
        "/images/atklatiesNoJauna/11. Aivars1.jpg",
        "/images/atklatiesNoJauna/3B4A4673.jpg",
        "/images/atklatiesNoJauna/13. Monika.jpg",
        "/images/atklatiesNoJauna/monika.jpg",
        "/images/atklatiesNoJauna/3B4A4673.jpg",
        "/images/atklatiesNoJauna/1. Modris.jpg",
        "/images/atklatiesNoJauna/modris.jpg",
        "/images/atklatiesNoJauna/3B4A0846.jpg",
      ],
    },
    {
      title: "GUDRO SUŅU BRĪVDIENAS",
      description: "...",
      image: "/images/gudro-sunu/izstades-foto/balts-smaida.jpg",
      longDescription: "...",
      images: [
        "/images/gudro-sunu/izstades-foto/cetri-sniega.jpg",
        "/images/gudro-sunu/izstades-foto/melns.jpg",
        "/images/gudro-sunu/izstades-foto/divi-egles.jpg",
        "/images/gudro-sunu/izstades-foto/mazs-melns.jpg",
        "/images/gudro-sunu/izstades-foto/balts-lido.jpg",
        "/images/gudro-sunu/izstades-foto/melns-plava.jpg",
        "/images/gudro-sunu/izstades-foto/mazs-lec.jpg",
        "/images/gudro-sunu/izstades-foto/melns-laipa.jpg",
        "/images/gudro-sunu/izstades-foto/mazs-saulrieta.jpg",
        "/images/gudro-sunu/izstades-foto/saulriets.jpg",
        "/images/gudro-sunu/izstades-foto/melns-brien.jpg",
        "/images/gudro-sunu/izstades-foto/gul.jpg",
        "/images/gudro-sunu/izstades-foto/melns-pupoli.jpg",
        "/images/gudro-sunu/izstades-foto/elfa.jpg",
        "/images/gudro-sunu/izstades-foto/melns-smiltis.jpg",
        "/images/gudro-sunu/izstades-foto/peld.jpg",
        "/images/gudro-sunu/izstades-foto/balts-biblioteka.jpg",
        "/images/gudro-sunu/izstades-foto/divi-peld.jpg",
        "/images/gudro-sunu/izstades-foto/balts-sez.jpg",
        "/images/gudro-sunu/izstades-foto/mazs-saule.jpg",
        "/images/gudro-sunu/izstades-foto/liga-riga.jpg",
        "/images/gudro-sunu/izstades-foto/meza.jpg",
        "/images/gudro-sunu/izstades-foto/melns-smaida.jpg",
        "/images/gudro-sunu/izstades-foto/sniega.jpg",
        "/images/gudro-sunu/izstades-foto/balts-smaida.jpg",
        "/images/gudro-sunu/izstades-foto/skrien-meza.jpg",
        "/images/gudro-sunu/izstades-foto/divi-skrien-meza.jpg",
        "/images/gudro-sunu/izstades-foto/balts-sniega.jpg",
      ],
    },
    {
      title: "ATKLĀTIES NO JAUNA",
      description: "...",
      image: "/images/atklaties-no-jauna/izstades-foto/elza-zirgs.jpg",
      longDescription: "...",
      image1: "/images/atklaties-no-jauna/izstades-foto/krekls.jpg",
      image2: "/images/atklaties-no-jauna/izstades-foto/koks.jpg",
      image3: "/images/atklaties-no-jauna/izstades-foto/upe.jpg",
      image4: "/images/atklaties-no-jauna/izstades-foto/acis.jpg",
      image5: "/images/atklaties-no-jauna/izstades-foto/plava.jpg",
      image6: "/images/atklaties-no-jauna/izstades-foto/anda.jpg",
      image7: "/images/atklaties-no-jauna/izstades-foto/ziema-avots.jpg",
      image8: "/images/atklaties-no-jauna/izstades-foto/elza-zirgs.jpg",
      image9: "/images/atklaties-no-jauna/izstades-foto/smilga.jpg",
      image10: "/images/atklaties-no-jauna/izstades-foto/elza-gul.jpg",
      image11: "/images/atklaties-no-jauna/izstades-foto/lakats.jpg",
      image12: "/images/atklaties-no-jauna/izstades-foto/zirgap-acs.jpg",
      image13: "/images/atklaties-no-jauna/izstades-foto/smiltis-slapjs.jpg",
      image14: "/images/atklaties-no-jauna/izstades-foto/mati.jpg",
      image15: "/images/atklaties-no-jauna/izstades-foto/studija.jpg",
      image16: "/images/atklaties-no-jauna/izstades-foto/rokas.jpg",
      image17: "/images/atklaties-no-jauna/izstades-foto/veja.jpg",
      image18: "/images/atklaties-no-jauna/izstades-foto/meza.jpg",
      image19: "/images/atklaties-no-jauna/izstades-foto/maja.jpg",
      image20: "/images/atklaties-no-jauna/izstades-foto/cuska.jpg",
      image21: "/images/atklaties-no-jauna/izstades-foto/supoles.jpg",
      image22: "/images/atklaties-no-jauna/izstades-foto/elina.tif",
      image23: "/images/atklaties-no-jauna/izstades-foto/durvis.jpg",
      image24: "/images/atklaties-no-jauna/izstades-foto/saknes.jpg",
      image25: "/images/atklaties-no-jauna/izstades-foto/puce.jpg",
      image26: "/images/atklaties-no-jauna/izstades-foto/laiva.jpg",
      image27: "/images/atklaties-no-jauna/izstades-foto/maika.jpg",
      image28: "/images/atklaties-no-jauna/izstades-foto/ragi.jpg",
      image29: "/images/atklaties-no-jauna/izstades-foto/elza-zirgs.jpg",
    },
    {
      title: "MĒS ESAM ŠEIT",
      image: "/images/mes-esam-seit/talsi/IMG_8713 resisede.jpg",
      images: [
        "/images/mes-esam-seit/talsi/20170114-IMG_2508-444Edit.jpg",
        "/images/mes-esam-seit/talsi/IMG_9972r.jpg",
        "/images/mes-esam-seit/talsi/20170114-IMG_2007.jpg",
        "/images/mes-esam-seit/talsi/20170114-IMG_2256sn d.jpg",
        "/images/mes-esam-seit/talsi/20170129-IMG_5914.jpg",
        "/images/mes-esam-seit/talsi/20170219-IMG_8056-Recovered.jpg",
        "/images/mes-esam-seit/talsi/20170219-IMG_8484.jpg",
        "/images/mes-esam-seit/talsi/20170226-IMG_8797 metinatajs.jpg",
        "/images/mes-esam-seit/talsi/20170311-IMG_0005-gat.jpg",
        "/images/mes-esam-seit/talsi/20170311-IMG_0193 gatis.jpg",
        "/images/mes-esam-seit/talsi/20170311-IMG_9498.jpg",
        "/images/mes-esam-seit/talsi/20170313-IMG_0516.jpg",
        "/images/mes-esam-seit/talsi/20170326-IMG_0959.jpg",
        "/images/mes-esam-seit/talsi/20170327-IMG_1465.jpg",
        "/images/mes-esam-seit/talsi/20170402-IMG_1910.jpg",
        "/images/mes-esam-seit/talsi/20170404-IMG_2396.jpg",
        "/images/mes-esam-seit/talsi/IMG_0538gt aina.jpg",
        "/images/mes-esam-seit/talsi/IMG_2168ii.jpg",
        "/images/mes-esam-seit/talsi/IMG_2987.jpg",
        "/images/mes-esam-seit/talsi/IMG_3120.jpg",
        "/images/mes-esam-seit/talsi/IMG_3401.jpg",
        "/images/mes-esam-seit/talsi/IMG_4082.jpg",
        "/images/mes-esam-seit/talsi/20170113-IMG_1832.jpg",
        "/images/mes-esam-seit/talsi/IMG_5958.jpg",
        "/images/mes-esam-seit/talsi/IMG_6697.jpg",
        "/images/mes-esam-seit/talsi/IMG_8713 resisede.jpg",
        "/images/mes-esam-seit/talsi/IMG_9037 ilze.jpg",
        "/images/mes-esam-seit/talsi/IMG_9890.jpg",
        "/images/mes-esam-seit/talsi/20170429-IMG_2410.jpg",
      ],
    },
    {
      title: "IZAUGT ĢIMENĒ",
      image: "/images/izaugt-gimene/046A2085re.jpg",
      images: [
        "/images/izaugt-gimene/046A0028.jpg",
        "/images/izaugt-gimene/046A0068e.jpg",
        "/images/izaugt-gimene/046A0170re.jpg",
        "/images/izaugt-gimene/046A0334re.jpg",
        "/images/izaugt-gimene/046A1489re.jpg",
        "/images/izaugt-gimene/046A1673re.jpg",
        "/images/izaugt-gimene/046A1735.jpg",
        "/images/izaugt-gimene/046A1880e.jpg",
        "/images/izaugt-gimene/046A2030re.jpg",
        "/images/izaugt-gimene/046A2085re.jpg",
        "/images/izaugt-gimene/046A2155e.jpg",
        "/images/izaugt-gimene/046A2424gatavs.jpg",
        "/images/izaugt-gimene/046A5501_.jpg",
        "/images/izaugt-gimene/046A5567.jpg",
        "/images/izaugt-gimene/046A5632.jpg",
        "/images/izaugt-gimene/046A8644-Edit.jpg",
        "/images/izaugt-gimene/046A8736.jpg",
        "/images/izaugt-gimene/046A8950re.jpg",
        "/images/izaugt-gimene/046A9146.jpg",
        "/images/izaugt-gimene/046A9195e.jpg",
        "/images/izaugt-gimene/046A9312.jpg",
        "/images/izaugt-gimene/046A9406re.jpg",
        "/images/izaugt-gimene/046A9951e.jpg",
        "/images/izaugt-gimene/046A9956 e.jpg",
        "/images/izaugt-gimene/046A087011re.jpg",
        "/images/izaugt-gimene/046A8985111e.jpg",
        "/images/izaugt-gimene/IMG_1441-200-2e.jpg",
        "/images/izaugt-gimene/IMG_1894-200 w.jpg",
        "/images/izaugt-gimene/IMG_4225-Edit e.jpg",
        "/images/izaugt-gimene/IMG_6640-2001.jpg",
        "/images/izaugt-gimene/IMG_7796-Edit-Edit re.jpg",
        "/images/izaugt-gimene/IMG_9565.jpg",
      ]
    },
    {
      title: "LATVIJAS BĒRNI",
    },
    {
      title: "VIENA DIENA BIBLIOTĒKAS DZĪVĒ",
    },
    {
      title: "CERĪBU LAIKS",
    },
    {
      title: "VIŅA",
    },
  ]
}

export default getExibitions
